-- COUNTRY TABLE
CREATE TABLE country (
id INT AUTO_INCREMENT PRIMARY KEY,
country_name VARCHAR(100) NOT NULL
);


-- STATE TABLE
CREATE TABLE state (
id INT AUTO_INCREMENT PRIMARY KEY,
statename VARCHAR(100) NOT NULL,
country_id INT NOT NULL,
FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE CASCADE
);


-- EMPLOYEE TABLE
CREATE TABLE employee (
id INT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
email VARCHAR(150) NOT NULL,
salary DECIMAL(10,2) DEFAULT 0,
address TEXT,
city VARCHAR(100),
state_id INT,
country_id INT,
FOREIGN KEY (state_id) REFERENCES state(id) ON DELETE SET NULL,
FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE SET NULL
);